{ Parsed from AVFoundation.framework (iPhoneOS8.2) AVAnimation.h }
{ Created on Fri Mar 20 2:11:14 2015 }

{$ifdef EXTERNAL_SYMBOLS}
var
  AVCoreAnimationBeginTimeAtZero: CFTimeInterval { available in 10_7, 4_0 }; cvar; external;
  AVLayerVideoGravityResizeAspect: NSString { available in 10_7, 4_0 }; cvar; external;
  AVLayerVideoGravityResizeAspectFill: NSString { available in 10_7, 4_0 }; cvar; external;
  AVLayerVideoGravityResize: NSString { available in 10_7, 4_0 }; cvar; external;
{$endif}

