{ Parsed from AVFoundation.framework (iPhoneOS8.2) AVAudioProcessingSettings.h }
{ Created on Fri Mar 20 2:11:14 2015 }

{$ifdef EXTERNAL_SYMBOLS}
var
  AVAudioTimePitchAlgorithmLowQualityZeroLatency: NSString { available in 7_0 }; cvar; external;
  AVAudioTimePitchAlgorithmTimeDomain: NSString { available in 10_9, 7_0 }; cvar; external;
  AVAudioTimePitchAlgorithmSpectral: NSString { available in 10_9, 7_0 }; cvar; external;
  AVAudioTimePitchAlgorithmVarispeed: NSString { available in 10_9, 7_0 }; cvar; external;
{$endif}

