{ Parsed from Foundation.framework (iPhoneOS8.2) NSExtensionItem.h }
{ Created on Fri Mar 20 2:11:40 2015 }

{$ifdef EXTERNAL_SYMBOLS}
var
  NSExtensionItemAttributedTitleKey: NSString { available in 10_10, 8_0 }; cvar; external;
  NSExtensionItemAttributedContentTextKey: NSString { available in 10_10, 8_0 }; cvar; external;
  NSExtensionItemAttachmentsKey: NSString { available in 10_10, 8_0 }; cvar; external;
{$endif}