{ Parsed from Foundation.framework (iPhoneOS8.2) NSExtensionContext.h }
{ Created on Fri Mar 20 2:11:40 2015 }

{$if defined(__OBJC2__)defined(interface)defined(NSExtensionContext)defined(NSObject)}
{$ifdef EXTERNAL_SYMBOLS}
var
  NSExtensionItemsAndErrorsKey: NSString { available in 10_10, 8_0 }; cvar; external;
  NSExtensionHostWillEnterForegroundNotification: NSString { available in 8_2 }; cvar; external;
  NSExtensionHostDidEnterBackgroundNotification: NSString { available in 8_2 }; cvar; external;
  NSExtensionHostWillResignActiveNotification: NSString { available in 8_2 }; cvar; external;
  NSExtensionHostDidBecomeActiveNotification: NSString { available in 8_2 }; cvar; external;
{$endif}

{$endif}
