{ Parsed from CoreBluetooth.framework (iPhoneOS8.2) CBAdvertisementData.h }
{ Created on Fri Mar 20 2:10:49 2015 }

{$ifdef EXTERNAL_SYMBOLS}
var
  CBAdvertisementDataLocalNameKey: NSString; cvar; external;
  CBAdvertisementDataTxPowerLevelKey: NSString; cvar; external;
  CBAdvertisementDataServiceUUIDsKey: NSString; cvar; external;
  CBAdvertisementDataServiceDataKey: NSString; cvar; external;
  CBAdvertisementDataManufacturerDataKey: NSString; cvar; external;
  CBAdvertisementDataOverflowServiceUUIDsKey: NSString { available in NA, 6_0 }; cvar; external;
  CBAdvertisementDataIsConnectable: NSString { available in NA, 7_0 }; cvar; external;
  CBAdvertisementDataSolicitedServiceUUIDsKey: NSString { available in NA, 7_0 }; cvar; external;
{$endif}

