{ Parsed from CoreBluetooth.framework (iPhoneOS8.2) CBCentralManagerConstants.h }
{ Created on Fri Mar 20 2:10:49 2015 }

{$ifdef EXTERNAL_SYMBOLS}
var
  CBCentralManagerOptionShowPowerAlertKey: NSString { available in NA, 7_0 }; cvar; external;
  CBCentralManagerOptionRestoreIdentifierKey: NSString { available in NA, 7_0 }; cvar; external;
  CBCentralManagerScanOptionAllowDuplicatesKey: NSString; cvar; external;
  CBCentralManagerScanOptionSolicitedServiceUUIDsKey: NSString { available in NA, 7_0 }; cvar; external;
  CBConnectPeripheralOptionNotifyOnConnectionKey: NSString { available in NA, 6_0 }; cvar; external;
  CBConnectPeripheralOptionNotifyOnDisconnectionKey: NSString; cvar; external;
  CBConnectPeripheralOptionNotifyOnNotificationKey: NSString { available in NA, 6_0 }; cvar; external;
  CBCentralManagerRestoredStatePeripheralsKey: NSString { available in NA, 7_0 }; cvar; external;
  CBCentralManagerRestoredStateScanServicesKey: NSString { available in NA, 7_0 }; cvar; external;
  CBCentralManagerRestoredStateScanOptionsKey: NSString { available in NA, 7_0 }; cvar; external;
{$endif}

