{ Parsed from CoreBluetooth.framework (iPhoneOS8.2) CBPeripheralManagerConstants.h }
{ Created on Fri Mar 20 2:10:49 2015 }

{$ifdef EXTERNAL_SYMBOLS}
var
  CBPeripheralManagerOptionShowPowerAlertKey: NSString { available in NA, 7_0 }; cvar; external;
  CBPeripheralManagerOptionRestoreIdentifierKey: NSString { available in NA, 7_0 }; cvar; external;
  CBPeripheralManagerRestoredStateServicesKey: NSString { available in NA, 7_0 }; cvar; external;
  CBPeripheralManagerRestoredStateAdvertisementDataKey: NSString { available in NA, 7_0 }; cvar; external;
{$endif}

