{ Parsed from CoreText.framework (iPhoneOS8.2) CoreText.h }
{ Created on Fri Mar 20 2:11:07 2015 }

{$ifndef __CORETEXT__}

{$ifdef TYPES}
const
  kCTVersionNumber10_5 = $00020000;
  kCTVersionNumber10_5_2 = $00020001;
  kCTVersionNumber10_5_3 = $00020002;
  kCTVersionNumber10_5_5 = $00020003;
  kCTVersionNumber10_6 = $00030000;
  kCTVersionNumber10_7 = $00040000;
  kCTVersionNumber10_8 = $00050000;
  kCTVersionNumber10_9 = $00060000;
  kCTVersionNumber10_10 = $00070000;
{$endif}

{$endif}
