{ Parsed from CoreMotion.framework (iPhoneOS8.2) CMError.h }
{ Created on Fri Mar 20 2:10:52 2015 }

{$ifdef TYPES}
const
  CMErrorNULL = 100;
  CMErrorDeviceRequiresMovement = 101;
  CMErrorTrueNorthNotAvailable = 102;
  CMErrorUnknown = 103;
  CMErrorMotionActivityNotAvailable = 104;
  CMErrorMotionActivityNotAuthorized = 105;
  CMErrorMotionActivityNotEntitled = 106;
  CMErrorInvalidParameter = 107;
  CMErrorInvalidAction = 108;
  CMErrorNotAvailable = 109;
  CMErrorNotEntitled = 110;
  CMErrorNotAuthorized = 111;
type
  CMError = clong;
{$endif}

