{ Parsed from StoreKit.framework (iPhoneOS8.2) SKError.h }
{ Created on Fri Mar 20 2:11:20 2015 }

{$ifdef EXTERNAL_SYMBOLS}
var
  SKErrorDomain: NSString { available in 3_0 }; cvar; external;
{$endif}

{$ifdef TYPES}
const
  SKErrorUnknown = 0;
  SKErrorClientInvalid = 1;
  SKErrorPaymentCancelled = 2;
  SKErrorPaymentInvalid = 3;
  SKErrorPaymentNotAllowed = 4;
  SKErrorStoreProductNotAvailable = 5;
{$endif}

